name: Our PR
on:
  pull_request:
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ref=${{ github.ref_name }}"
      - run: echo "name=${{ github.event_name }}"
      - run: echo "action=${{ github.event.action }}"
